spring:
  application:
    name: book-network-api
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /v3/api-docs
  default-produces-media-type: application/json

server:
  servlet:
    context-path: /api/v1/
